## Biography
Aditya Mahajan is Professor of Electrical and Computer Engineering at McGill University, Montreal, Canada. He is a member of the McGill Center of Intelligent Machines (CIM), Mila - Québec AI Institute, International Laboratory for Learning Systems (ILLS), and Groupe d'études et de recherche en analyse des décisions (GERAD). He received the B.Tech degree in Electrical Engineering from the Indian Institute of Technology, Kanpur, India and the MS and PhD degrees in Electrical Engineering and Computer Science from the University of Michigan, Ann Arbor, USA. He has held visiting appointments at the University of California, Berkeley and the University of Paris-Saclay.

He is a senior member of the IEEE and member of Professional Engineers Ontario. He currently serves as Associate Editor of IEEE Transactions on Automatic Control, IEEE Control Systems Letters, and Springer Mathematics of Control, Signal, and Systems. He was an Associate Editor of the IEEE Control Systems Society Conference Editorial Board from 2014 to 2017.

He is the recipient of the 2015 George Axelby Outstanding Paper Award, the 2016 NSERC Discovery Accelerator Award, the 2014 CDC Best Student Paper Award (as supervisor), and the 2016 NecSys Best Student Paper Award (as supervisor). His principal research interests include decentralized stochastic control, team theory, reinforcement learning, multi-armed bandits and information theory.
